apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-csi
  namespace: default
  labels:
    app: simple-csi
spec:
  selector:
    matchLabels:
      app: simple-csi
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  simple-csi
      labels:
        app: simple-csi
    spec:
      containers:
      - name: simple-csi
        image: "grantfl/simple-csi:latest"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always

